services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      - PORT=3000

  users_microservices:
    build: ./users-microservices
    volumes:
      - ./users-microservices/src:/usr/src/app/src
    command: pnpm start:dev

  payments_microservices:
    build: ./payments-microservices
    volumes:
      - ./payments-microservices/src:/usr/src/app/src
    command: pnpm start:dev

  nats:
    image: nats
    ports:
      - 4222:4222
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
